// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoaZ7KKmHWcX3QJL8MMSvuAClC-IzbueE',
    appId: '1:110789853091:web:63e6fb6b99ff5c5367a416',
    messagingSenderId: '110789853091',
    projectId: 'spajam2024-89f47',
    authDomain: 'spajam2024-89f47.firebaseapp.com',
    storageBucket: 'spajam2024-89f47.appspot.com',
    measurementId: 'G-X05MJ3DTFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU_XfOq9VJKiMqaFRH41Mtou2xGGLgOS8',
    appId: '1:110789853091:android:04d7e2cc702ba3dd67a416',
    messagingSenderId: '110789853091',
    projectId: 'spajam2024-89f47',
    storageBucket: 'spajam2024-89f47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVxpTW2PiGeY6j65WfRNv2nuJzjsbcViY',
    appId: '1:110789853091:ios:1bc42b81fc4f0df767a416',
    messagingSenderId: '110789853091',
    projectId: 'spajam2024-89f47',
    storageBucket: 'spajam2024-89f47.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVxpTW2PiGeY6j65WfRNv2nuJzjsbcViY',
    appId: '1:110789853091:ios:1bc42b81fc4f0df767a416',
    messagingSenderId: '110789853091',
    projectId: 'spajam2024-89f47',
    storageBucket: 'spajam2024-89f47.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoaZ7KKmHWcX3QJL8MMSvuAClC-IzbueE',
    appId: '1:110789853091:web:932f5f9143d96d0667a416',
    messagingSenderId: '110789853091',
    projectId: 'spajam2024-89f47',
    authDomain: 'spajam2024-89f47.firebaseapp.com',
    storageBucket: 'spajam2024-89f47.appspot.com',
    measurementId: 'G-PZY3B8GKHP',
  );
}
